name: Auto Approve for Specific Users

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is allowed to bypass rules
        env:
          ALLOWED_USERS: "petukhoudzmitry"
        run: |
          if echo "$ALLOWED_USERS" | grep -w "$GITHUB_ACTOR"; then
            echo "User $GITHUB_ACTOR is allowed to auto-approve."
            echo "APPROVE_ALLOWED=true" >> $GITHUB_ENV
          else
            echo "User $GITHUB_ACTOR is NOT allowed to auto-approve."
            exit 0
          fi

      - name: Get Pull Request Number
        if: env.APPROVE_ALLOWED == 'true'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Approve Pull Request
        if: env.APPROVE_ALLOWED == 'true'
        run: gh pr review --approve "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
