name: Gradle Build (Restricted)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  CheckUserPermission:
    runs-on: ubuntu-latest
    outputs:
      allowed: ${{ steps.check-permission.outputs.allowed }}

    steps:
      - name: Check user permission
        id: check-permission
        run: |
          ALLOWED_USERS=("ikvict07" "petukhoudzmitry")
          if [[ " ${ALLOWED_USERS[@]} " =~ " ${GITHUB_ACTOR} " ]]; then
            echo "User $GITHUB_ACTOR is allowed. Skipping build."
            echo "allowed=true" >> $GITHUB_ENV
          else
            echo "User $GITHUB_ACTOR is not allowed. Exiting."
            echo "allowed=false" >> $GITHUB_ENV
          fi
        shell: bash

  build:
    needs: CheckUserPermission
    runs-on: ubuntu-latest
    if: ${{ needs.CheckUserPermission.outputs.allowed == 'false' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '23'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Gradle build
        run: ./gradlew build
