name: Auto Approve for Specific Users

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set approval environment variable
        run: |
          ALLOWED_USERS=("petukhoudzmitry")

          if [[ " ${ALLOWED_USERS[@]} " =~ " $GITHUB_ACTOR " ]]; then
            echo "User $GITHUB_ACTOR is allowed to auto-approve."
            echo "APPROVE_ALLOWED=true" >> $GITHUB_ENV
          else
            echo "User $GITHUB_ACTOR is NOT allowed to auto-approve."
            exit 0
          fi

      - name: Check pr author
        if: env.APPROVE_ALLOWED == 'true'
        run: |
          PR_AUTHOR=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH")
          echo "Pull request author: $PR_AUTHOR"
          if [[ "$PR_AUTHOR" == "ikvict07" ]]; then
            echo "PR author is ikvict07, skipping auto-approval."
            exit 0
          else
            echo "PR author is not ikvict07, continuing with auto-approval."
          fi

      - name: Get Pull Request Number
        if: env.APPROVE_ALLOWED == 'true'
        run: echo "PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

      - name: Approve pull request
        if: env.APPROVE_ALLOWED == 'true'
        run: gh pr review --approve "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
