name: Sync Main to Docs and Generate Javadoc
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  merge-to-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync documentation branch
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git fetch origin documentation || true
          git checkout documentation || git checkout -b documentation
          git reset --hard origin/main
          git push -f origin documentation

  generate-javadoc:
    needs: merge-to-docs
    runs-on: ubuntu-latest
    steps:
      - name: Make required dirs
        run: |
          mkdir -p docs
          touch docs/.gitkeep
      - name: Checkout documentation branch
        uses: actions/checkout@v4
        with:
          ref: documentation
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '23'

      - name: Run Javadoc
        run: ./gradlew javadoc

      - name: Configure Git for Javadoc Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Javadoc
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git add docs
          git commit -m "Update Javadoc" || echo "No changes to commit"
          git push origin documentation
